### ISSUE TITLE
About "Bad Request: Unable to validate payload size, the parameter 'text' is null or empty."

### ISSUE THREAD

**Issue by mozgbrasil** [Samurai016/PoTranslator#1]
Hello

Good morning my friend

I am trying to translate the following document but the alert "Bad Request: Unable to validate payload size, the parameter 'text' is null or empty."

I need to translate the following document into Portuguese

https://gitlab.com/Nalin-x-Linux/lios-3/uploads/41a2fec701a0dcfb47c6a0ddb054db6a/pt_BR.po

![Captura de tela de 2020-01-20 17-09-23](https://user-images.githubusercontent.com/17202780/72754837-add1b380-3ba7-11ea-984d-2740af42ffe4.png)

**Comment by Samurai016** [comment]
I @mozgbrasil ,
I just updated the tool, I found the bug and solved it, I also improved the ui.
Update the tool from npm to version 1.0.3 and try another time the translation.
I hope I helped you, thank you.
